### ISSUE TITLE
Useless getBackgroundDataSetting

### ISSUE THREAD

**Issue by frankFic** [firetech/PactrackDroid#12]
Dear developers of PactrackDroid,

I am a student majoring in Computer Science. We are trying to collect existing bug reports and fixes of to help detect and fix similar bugs of other active applications.

I have detected that method ConnectivityManager.getBackgroundDataSetting() is used on line 108 in `nu.firetech.android.pactrack.frontend.ConfigView` and line 64 `nu.firetech.android.pactrack.backend.ServiceStarter`.

However, since this method always return true after API level 14 (Noted in [API Guide](http://developer.android.com/intl/zh-cn/reference/android/net/ConnectivityManager.html#getBackgroundDataSetting())) and currently the minSDK version of PactrackDroid is 14 so that calling this method is actually useless.
I found that PactrackDroid has been built since 2009, I think this API may be included long time ago, but now it seems to be outdated for your app.

Thanks a lot for your attention. Hope this information is useful for you.

**Comment by firetech** [comment]
Thanks. As you may have seen in the comments, we knew about the deprecation, but didn't realize we had dropped the support for the old versions that still needed it.
