### ISSUE TITLE
Postförskottsbetalnings paket sökning

### ISSUE THREAD

**Issue by RickardPettersson** [firetech/PactrackDroid#2]
Jag vet inte om det har med postförskottsbetalning  att göra alls men av någon anledning kan jag inte i din app söka på kollid:et AF109542749SE men på postens hemsida får jag fram information om det.

Se denna länk för posten: http://www.posten.se/tracktrace/TrackConsignments_do.jsp?trackntraceAction=saveSearch&logisticCustomerNumber=&referenceNumber=&lang=SE&loginHandlerImplClass=se.posten.pse.framework.security.applicationImpl.tracktrace.LoginHandlerImpl&internalPageNumber=0&doNotShowInHistory=true&consignmentId=AF109542749SE

**Comment by blunden** [comment]
Detta bör förresten vara fixat i senare versioner av denna app tack vara postens nya API.
