### ISSUE TITLE
Correct theme does not apply to Settings Toolbar

### ISSUE THREAD

**Issue by blunden** [firetech/PactrackDroid#4]
The Toolbar in Settings isn't using the intended Light.DarkActionBar look despite being configured as described in the link below. Seems to be a regression from some time ago.

http://android-developers.blogspot.se/2014/10/appcompat-v21-material-design-for-pre.html

Or

http://stackoverflow.com/questions/26503149/how-do-i-style-appcompat-v7-toolbar-like-theme-appcompat-light-darkactionbar

**Comment by blunden** [comment]
@firetech I have yet to figure this out. I suggest we push the new material design release to the Play Store anyway.

**Comment by firetech** [comment]
Roger that.

I would like the relevant text (the ones that aren't bold) in the parcel
view to be darker (black?), like in the parcel list, for better
readability, but I think I can fix that myself.

We need to make a release with the new PostNord API before the end of March
anyhow. That's on my TODO list, I've just had a lot on my mind lately.

**Comment by blunden** [comment]
It should probably be black with an opacity of 87%.

https://www.google.com/design/spec/style/typography.html#typography-other-typographic-guidelines
https://www.google.com/design/spec/style/color.html#color-text-background-colors

**Comment by blunden** [comment]
Great. The use of preference headers was what required the problematic Toolbar. What is left to address until the Play Store release?

**Comment by firetech** [comment]
Nothing. :)

![Signed APK generated](https://dl.dropboxusercontent.com/u/44217789/apk_built.png)

I just have to make some new screenshots (my favorite pastime /s)...
