### ISSUE TITLE
Double Update actions in two-pane layout (tablets)

### ISSUE THREAD

**Issue by firetech** [firetech/PactrackDroid#6]
When viewing a parcel in two-pane layout (on a tablet/xlarge display), both the "Update" and "Update All" actions are visible in the action bar, with the same icon. A bit confusing.

I see two possible ways of solving this:

1) Set showAsAction for the "Update All" menu item to "never" in two pane layouts.
2) Change the icon for either of the actions to make the situation clearer. For example adding a '1' to the "Update" icon or something else to the "Update All" icon.

I would prefer option 2, but I don't feel confident in editing the icons. Option 1, however, can be implemented in just a few minutes.

**Comment by firetech** [comment]
@blunden can you take a look at creating an "update one" icon whenever you have time?

**Comment by blunden** [comment]
Ok

**Comment by blunden** [comment]
This should solve that.

https://github.com/firetech/PactrackDroid/commit/ae5e0c37694d1e67f25a9117099d8afb4f933768

**Comment by firetech** [comment]
Thanks! Looks nice! :)
